SELECT "Id",
       "OrganizationId",
       "Email",
       "Role",
       "Token",
       "ExpiresAt",
       "InvitedByUserId",
       "AcceptedAt",
       "RevokedAt",
       "CreatedAt",
       "UpdatedAt",
       "CreatedById",
       "UpdatedById",
       "IsDeleted",
       "DeletedAt",
       "DeletedById",
       "RowVersion"
FROM public."OrganizationInvitations";