CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "AgentPhoneNumbers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PhoneNumber" text NOT NULL,
    "AgentId" integer NOT NULL,
    CONSTRAINT "PK_AgentPhoneNumbers" PRIMARY KEY ("Id")
);

CREATE TABLE "Features" (
    "Id" uuid NOT NULL,
    "Code" character varying(100) NOT NULL,
    "DisplayName" character varying(200) NOT NULL,
    "Description" character varying(1000),
    "Category" character varying(100),
    "IsActive" boolean NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedById" uuid,
    "UpdatedById" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedById" uuid,
    "RowVersion" bytea NOT NULL,
    CONSTRAINT "PK_Features" PRIMARY KEY ("Id")
);

CREATE TABLE test_entities (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_test_entities" PRIMARY KEY ("Id")
);

CREATE TABLE "AccessAuditLogs" (
    "Id" uuid NOT NULL,
    "UserId" uuid,
    "RequestingUserId" uuid NOT NULL,
    "OrganizationId" uuid NOT NULL,
    "Action" character varying(50) NOT NULL,
    "EntityType" character varying(100) NOT NULL,
    "EntityId" uuid NOT NULL,
    "ResourceType" character varying(50) NOT NULL,
    "ResourceId" uuid NOT NULL,
    "ContactId" uuid,
    "AccessGranted" boolean NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "IpAddress" character varying(45),
    "UserAgent" character varying(500),
    "Reason" character varying(500) NOT NULL,
    "PrivacyTags" jsonb NOT NULL,
    "Metadata" character varying(2000),
    "AccessedAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedById" uuid,
    "UpdatedById" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedById" uuid,
    "RowVersion" bytea NOT NULL,
    CONSTRAINT "PK_AccessAuditLogs" PRIMARY KEY ("Id")
);

CREATE TABLE "ActionItem" (
    "Id" text NOT NULL,
    "Text" text NOT NULL,
    "Status" text NOT NULL,
    "Type" text NOT NULL,
    "Priority" text,
    "AssignedTo" uuid,
    "DueBy" timestamp with time zone,
    "CompletedAt" timestamp with time zone,
    "InteractionId" uuid,
    CONSTRAINT "PK_ActionItem" PRIMARY KEY ("Id")
);

CREATE TABLE "Address" (
    "Id" uuid NOT NULL,
    "Street1" character varying(200) NOT NULL,
    "Street2" character varying(200),
    "City" character varying(100) NOT NULL,
    "State" character varying(100) NOT NULL,
    "PostalCode" character varying(20) NOT NULL,
    "Country" character varying(2) NOT NULL,
    "Type" character varying(50),
    "IsPrimary" boolean NOT NULL,
    "Notes" character varying(500),
    "ContactId" uuid,
    "OrganizationId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedById" uuid,
    "UpdatedById" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedById" uuid,
    "RowVersion" bytea NOT NULL,
    CONSTRAINT "PK_Address" PRIMARY KEY ("Id")
);

CREATE TABLE "AgentAssignments" (
    "Id" uuid NOT NULL,
    "EmmaAnalysisId" uuid NOT NULL,
    "AgentId" uuid NOT NULL,
    "AssignmentType" text NOT NULL,
    "AssignedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AgentAssignments" PRIMARY KEY ("Id")
);

CREATE TABLE "Agents" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "AgentType" character varying(50) NOT NULL,
    "Configuration" character varying(4000),
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastActive" timestamp with time zone,
    "OrganizationId" uuid,
    "CreatedById" uuid,
    "SubscriptionUserId" uuid,
    CONSTRAINT "PK_Agents" PRIMARY KEY ("Id")
);

CREATE TABLE "Attachment" (
    "Id" text NOT NULL,
    "Name" text NOT NULL,
    "Type" text NOT NULL,
    "Size" bigint NOT NULL,
    "Url" text,
    "PreviewUrl" text,
    "InteractionId" uuid,
    CONSTRAINT "PK_Attachment" PRIMARY KEY ("Id")
);

CREATE TABLE "CallMetadata" (
    "MessageId" uuid NOT NULL,
    "ClientPhoneNumber" text NOT NULL,
    "DurationInSeconds" integer NOT NULL,
    "DirectionBasedOnAgent" integer NOT NULL,
    "Status" integer NOT NULL,
    "ReferenceId" text NOT NULL,
    CONSTRAINT "PK_CallMetadata" PRIMARY KEY ("MessageId")
);

CREATE TABLE "ContactAssignments" (
    "Id" uuid NOT NULL,
    "ContactId" uuid NOT NULL,
    "ServiceContactId" uuid NOT NULL,
    "AssignedByUserId" uuid NOT NULL,
    "OrganizationId" uuid NOT NULL,
    "Purpose" character varying(500) NOT NULL,
    "Status" integer NOT NULL,
    "Priority" integer NOT NULL,
    "InteractionId" uuid,
    "ClientRequest" character varying(1000),
    "AssignedAt" timestamp with time zone NOT NULL,
    "CompletedAt" timestamp with time zone,
    "FollowUpAt" timestamp with time zone,
    "WasUsed" boolean NOT NULL,
    "ClientRating" numeric,
    "ClientFeedback" character varying(1000),
    "OutcomeNotes" character varying(1000),
    "InternalNotes" character varying(1000),
    "ReferralDisclosureProvided" boolean NOT NULL,
    "ReferralDisclosureDate" timestamp with time zone,
    "LiabilityDisclaimerAcknowledged" boolean NOT NULL,
    "LiabilityDisclaimerDate" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CustomFields" jsonb,
    CONSTRAINT "PK_ContactAssignments" PRIMARY KEY ("Id")
);

CREATE TABLE "ContactCollaborators" (
    "Id" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "ContactId" uuid NOT NULL,
    "CollaboratorUserId" uuid NOT NULL,
    "GrantedByUserId" uuid NOT NULL,
    "OrganizationId" uuid NOT NULL,
    "Role" integer NOT NULL,
    "CanAccessBusinessInteractions" boolean NOT NULL,
    "CanAccessPersonalInteractions" boolean NOT NULL,
    "CanCreateInteractions" boolean NOT NULL,
    "CanEditInteractions" boolean NOT NULL,
    "CanAssignResources" boolean NOT NULL,
    "CanAccessFinancialData" boolean NOT NULL,
    "CanEditContactDetails" boolean NOT NULL,
    "CanManageCollaborators" boolean NOT NULL,
    "CanViewAuditLogs" boolean NOT NULL,
    "Reason" character varying(500),
    "ExpiresAt" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    "ContactId1" uuid,
    CONSTRAINT "PK_ContactCollaborators" PRIMARY KEY ("Id")
);

CREATE TABLE "Contacts" (
    "Id" uuid NOT NULL,
    "OrganizationId" uuid NOT NULL,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "MiddleName" character varying(100),
    "PreferredName" character varying(100),
    "Title" character varying(50),
    "JobTitle" character varying(200),
    "Company" character varying(200),
    "Department" character varying(200),
    "RelationshipState" integer NOT NULL,
    "LastContactedAt" timestamp with time zone,
    "NextFollowUpAt" timestamp with time zone,
    "Source" character varying(100),
    "OwnerId" uuid,
    "PreferredContactMethod" character varying(50),
    "PreferredContactTime" character varying(50),
    "Notes" text,
    "ProfilePictureUrl" character varying(500),
    "PhoneNumbers" jsonb NOT NULL,
    "IsActiveClient" boolean NOT NULL,
    "ClientSince" timestamp with time zone,
    "CompanyName" text,
    "LicenseNumber" text,
    "Specialties" text[] NOT NULL,
    "ServiceAreas" text[] NOT NULL,
    "Rating" numeric,
    "ReviewCount" integer NOT NULL,
    "IsPreferred" boolean NOT NULL,
    "Website" text,
    "Tags" jsonb NOT NULL,
    "LeadSource" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CustomFields" jsonb,
    "AssignedToId" uuid,
    "AgentId" uuid,
    "CreatedById" uuid,
    "UpdatedById" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedById" uuid,
    "RowVersion" bytea NOT NULL,
    CONSTRAINT "PK_Contacts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Contacts_Agents_AgentId" FOREIGN KEY ("AgentId") REFERENCES "Agents" ("Id")
);

CREATE TABLE "ContactSummaries" (
    "Id" text NOT NULL,
    "ContactId" uuid NOT NULL,
    "OrganizationId" uuid NOT NULL,
    "SummaryType" text NOT NULL,
    "SummaryText" text NOT NULL,
    "InteractionCount" integer NOT NULL,
    "EarliestInteraction" timestamp with time zone NOT NULL,
    "LatestInteraction" timestamp with time zone NOT NULL,
    "KeyMilestones" jsonb NOT NULL,
    "ImportantPreferences" jsonb NOT NULL,
    "CustomFields" jsonb NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastUpdated" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ContactSummaries" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ContactSummaries_Contacts_ContactId" FOREIGN KEY ("ContactId") REFERENCES "Contacts" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ContactStateHistory" (
    "Id" uuid NOT NULL,
    "ContactId" uuid NOT NULL,
    "FromState" integer NOT NULL,
    "ToState" integer NOT NULL,
    "TransitionDate" timestamp with time zone NOT NULL,
    "Reason" character varying(1000),
    "ChangedByUserId" uuid,
    "Metadata" jsonb,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedById" uuid,
    "UpdatedById" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedById" uuid,
    "RowVersion" bytea NOT NULL,
    CONSTRAINT "PK_ContactStateHistory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ContactStateHistory_Contacts_ContactId" FOREIGN KEY ("ContactId") REFERENCES "Contacts" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ContactStates" (
    "Id" text NOT NULL,
    "ContactId" uuid NOT NULL,
    "OrganizationId" uuid NOT NULL,
    "CurrentStage" text NOT NULL,
    "NextMilestone" text,
    "Priority" text NOT NULL,
    "AssignedUserId" uuid,
    "PendingTasks" jsonb NOT NULL,
    "OpenObjections" jsonb NOT NULL,
    "ImportantDates" jsonb NOT NULL,
    "PropertyInfo" jsonb NOT NULL,
    "FinancialInfo" jsonb NOT NULL,
    "CustomFields" jsonb NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastUpdated" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ContactStates" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ContactStates_Contacts_ContactId" FOREIGN KEY ("ContactId") REFERENCES "Contacts" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ConversationSummaries" (
    "Id" uuid NOT NULL,
    "InteractionId" uuid NOT NULL,
    "QualityScore" double precision,
    "SummaryText" text,
    CONSTRAINT "PK_ConversationSummaries" PRIMARY KEY ("Id")
);

CREATE TABLE "DetailedNotes" (
    "Id" uuid NOT NULL,
    "InteractionId" uuid NOT NULL,
    "NoteText" text NOT NULL,
    "SourceAgent" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastUpdated" timestamp with time zone,
    CONSTRAINT "PK_DetailedNotes" PRIMARY KEY ("Id")
);

CREATE TABLE "DeviceTokens" (
    "UserId" uuid NOT NULL,
    "DeviceId" character varying(255) NOT NULL,
    "Token" character varying(500) NOT NULL,
    "Platform" character varying(50) NOT NULL,
    "DeviceName" character varying(100),
    "DeviceModel" character varying(100),
    "OsVersion" character varying(50),
    "AppVersion" character varying(50),
    "IsActive" boolean NOT NULL,
    "LastUsedAt" timestamp with time zone,
    "Id" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedById" uuid,
    "UpdatedById" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedById" uuid,
    "RowVersion" bytea NOT NULL,
    CONSTRAINT "PK_DeviceTokens" PRIMARY KEY ("UserId", "DeviceId")
);

CREATE TABLE "EmailAddresses" (
    "Id" uuid NOT NULL,
    "Address" character varying(255) NOT NULL,
    "IsPrimary" boolean NOT NULL,
    "IsVerified" boolean NOT NULL,
    "Type" character varying(50),
    "UserId" uuid,
    "ContactId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "ContactId1" uuid,
    "CreatedById" uuid,
    "UpdatedById" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedById" uuid,
    "RowVersion" bytea NOT NULL,
    CONSTRAINT "PK_EmailAddresses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EmailAddresses_Contacts_ContactId" FOREIGN KEY ("ContactId") REFERENCES "Contacts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EmailAddresses_Contacts_ContactId1" FOREIGN KEY ("ContactId1") REFERENCES "Contacts" ("Id")
);

CREATE TABLE "EmmaAnalyses" (
    "Id" uuid NOT NULL,
    "MessageId" uuid NOT NULL,
    "LeadStatus" character varying(50) NOT NULL,
    "RecommendedStrategy" character varying(500) NOT NULL,
    "ComplianceFlags" text[] NOT NULL,
    "FollowupGuidance" character varying(2000) NOT NULL,
    "ConfidenceScore" integer,
    "ModelVersion" character varying(50),
    "Metadata" jsonb,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedById" uuid,
    "UpdatedById" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedById" uuid,
    "RowVersion" bytea NOT NULL,
    CONSTRAINT "PK_EmmaAnalyses" PRIMARY KEY ("Id")
);

CREATE TABLE "EmmaTask" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TaskType" text NOT NULL,
    "Description" text NOT NULL,
    "DueDate" timestamp with time zone NOT NULL,
    "EmmaAnalysisId" uuid,
    CONSTRAINT "PK_EmmaTask" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EmmaTask_EmmaAnalyses_EmmaAnalysisId" FOREIGN KEY ("EmmaAnalysisId") REFERENCES "EmmaAnalyses" ("Id")
);

CREATE TABLE "InteractionEmbeddings" (
    "Id" text NOT NULL,
    "ContactId" uuid NOT NULL,
    "InteractionId" uuid NOT NULL,
    "OrganizationId" uuid NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "Type" text NOT NULL,
    "Summary" text NOT NULL,
    "RawContent" text,
    "EmbeddingModel" text NOT NULL,
    "ModelVersion" text NOT NULL,
    "PrivacyTags" jsonb NOT NULL,
    "ExtractedEntities" jsonb NOT NULL,
    "Topics" jsonb NOT NULL,
    "SentimentScore" double precision NOT NULL,
    "CustomFields" jsonb NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_InteractionEmbeddings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InteractionEmbeddings_Contacts_ContactId" FOREIGN KEY ("ContactId") REFERENCES "Contacts" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Interactions" (
    "Id" uuid NOT NULL,
    "OrganizationId" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "ContactId" uuid NOT NULL,
    "ParentInteractionId" uuid,
    "ThreadId" text,
    "Version" integer NOT NULL,
    "Type" text NOT NULL,
    "Direction" text NOT NULL,
    "Status" text NOT NULL,
    "Priority" text NOT NULL,
    "Subject" text,
    "Content" text,
    "Summary" text,
    "VectorEmbedding" real[],
    "SentimentScore" real,
    "SentimentLabel" text,
    "PrivacyLevel" text NOT NULL,
    "Confidentiality" text,
    "RetentionPolicy" text,
    "IsRead" boolean NOT NULL,
    "IsStarred" boolean NOT NULL,
    "FollowUpRequired" boolean NOT NULL,
    "Channel" text NOT NULL,
    "Tags" text[] NOT NULL,
    "StartedAt" timestamp with time zone,
    "EndedAt" timestamp with time zone,
    "ScheduledFor" timestamp with time zone,
    "DurationSeconds" integer,
    "FollowUpBy" timestamp with time zone,
    "CreatedById" uuid NOT NULL,
    "AssignedToUserId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "DeletedAt" timestamp with time zone,
    "AgentId" uuid,
    "UpdatedById" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedById" uuid,
    "RowVersion" bytea NOT NULL,
    CONSTRAINT "PK_Interactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Interactions_Agents_AgentId" FOREIGN KEY ("AgentId") REFERENCES "Agents" ("Id"),
    CONSTRAINT "FK_Interactions_Contacts_ContactId" FOREIGN KEY ("ContactId") REFERENCES "Contacts" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Interactions_Interactions_ParentInteractionId" FOREIGN KEY ("ParentInteractionId") REFERENCES "Interactions" ("Id")
);

CREATE TABLE "RelatedEntity" (
    "Id" uuid NOT NULL,
    "Type" text NOT NULL,
    "InteractionId" uuid,
    CONSTRAINT "PK_RelatedEntity" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RelatedEntity_Interactions_InteractionId" FOREIGN KEY ("InteractionId") REFERENCES "Interactions" ("Id")
);

CREATE TABLE "SummaryOfSummaries" (
    "Id" uuid NOT NULL,
    "InteractionId" uuid,
    "ContactId" uuid,
    "SummaryText" text NOT NULL,
    "SourceAgent" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastUpdated" timestamp with time zone,
    CONSTRAINT "PK_SummaryOfSummaries" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SummaryOfSummaries_Contacts_ContactId" FOREIGN KEY ("ContactId") REFERENCES "Contacts" ("Id"),
    CONSTRAINT "FK_SummaryOfSummaries_Interactions_InteractionId" FOREIGN KEY ("InteractionId") REFERENCES "Interactions" ("Id")
);

CREATE TABLE "InteractionTranscriptions" (
    "Id" uuid NOT NULL,
    "InteractionId" uuid NOT NULL,
    "TranscriptionId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_InteractionTranscriptions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InteractionTranscriptions_Interactions_InteractionId" FOREIGN KEY ("InteractionId") REFERENCES "Interactions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Messages" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Payload" text NOT NULL,
    "AiResponse" text,
    "BlobStorageUrl" character varying(1000),
    "Type" integer NOT NULL,
    "OccurredAt" timestamp with time zone NOT NULL,
    "InteractionId" uuid NOT NULL,
    "Direction" integer NOT NULL,
    "Status" character varying(50) NOT NULL,
    "ErrorDetails" character varying(2000),
    "Metadata" jsonb,
    "AgentId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedById" uuid,
    "UpdatedById" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedById" uuid,
    "RowVersion" bytea NOT NULL,
    CONSTRAINT "PK_Messages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Messages_Agents_AgentId" FOREIGN KEY ("AgentId") REFERENCES "Agents" ("Id"),
    CONSTRAINT "FK_Messages_Interactions_InteractionId" FOREIGN KEY ("InteractionId") REFERENCES "Interactions" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Transcriptions" (
    "Id" uuid NOT NULL,
    "BlobStorageUrl" text NOT NULL,
    "Type" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "MessageId" uuid NOT NULL,
    CONSTRAINT "PK_Transcriptions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Transcriptions_Messages_MessageId" FOREIGN KEY ("MessageId") REFERENCES "Messages" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Organizations" (
    "Id" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Website" character varying(255),
    "PhoneNumber" character varying(50),
    "LogoUrl" character varying(500),
    "TimeZone" character varying(100),
    "Locale" character varying(20),
    "Currency" character varying(3),
    "Email" character varying(200) NOT NULL,
    "OwnerUserId" uuid NOT NULL,
    "IndustryCode" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "FubApiKey" character varying(100),
    "FubSystem" character varying(50),
    "FubSystemKey" character varying(100),
    "FubId" integer,
    "CreatedById" uuid,
    "UpdatedById" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedById" uuid,
    "RowVersion" bytea NOT NULL,
    CONSTRAINT "PK_Organizations" PRIMARY KEY ("Id")
);

CREATE TABLE "SubscriptionPlans" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    "Description" character varying(500),
    "OrganizationId" uuid NOT NULL,
    "MonthlyPrice" numeric(18,2) NOT NULL,
    "AnnualPrice" numeric(18,2),
    "MaxUsers" integer,
    "MaxContacts" integer,
    "MaxStorageMb" bigint,
    "CreatedById" uuid,
    "UpdatedById" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedById" uuid,
    "RowVersion" bytea NOT NULL,
    CONSTRAINT "PK_SubscriptionPlans" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SubscriptionPlans_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Users" (
    "Id" uuid NOT NULL,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "Password" character varying(255) NOT NULL,
    "FubApiKey" character varying(255),
    "FubUserId" integer,
    "IsActive" boolean NOT NULL,
    "IsAdmin" boolean NOT NULL,
    "Role" character varying(50),
    "OrganizationId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedById" uuid,
    "UpdatedById" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedById" uuid,
    "RowVersion" bytea NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id")
);

CREATE TABLE "OrganizationSubscription" (
    "Id" uuid NOT NULL,
    "OrganizationId" uuid NOT NULL,
    "SubscriptionPlanId" uuid NOT NULL,
    "SeatsLimit" integer NOT NULL,
    "StripeSubscriptionId" character varying(100),
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedById" uuid,
    "UpdatedById" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedById" uuid,
    "RowVersion" bytea NOT NULL,
    CONSTRAINT "PK_OrganizationSubscription" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrganizationSubscription_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrganizationSubscription_SubscriptionPlans_SubscriptionPlan~" FOREIGN KEY ("SubscriptionPlanId") REFERENCES "SubscriptionPlans" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SubscriptionPlanFeatures" (
    "SubscriptionPlanId" uuid NOT NULL,
    "FeatureId" uuid NOT NULL,
    "AddedAt" timestamp with time zone NOT NULL,
    "IsEnabled" boolean NOT NULL,
    "Limit" integer,
    "Notes" character varying(500),
    "FeatureId1" uuid,
    "Id" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedById" uuid,
    "UpdatedById" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedById" uuid,
    "RowVersion" bytea NOT NULL,
    CONSTRAINT "PK_SubscriptionPlanFeatures" PRIMARY KEY ("SubscriptionPlanId", "FeatureId"),
    CONSTRAINT "FK_SubscriptionPlanFeatures_Features_FeatureId" FOREIGN KEY ("FeatureId") REFERENCES "Features" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SubscriptionPlanFeatures_Features_FeatureId1" FOREIGN KEY ("FeatureId1") REFERENCES "Features" ("Id"),
    CONSTRAINT "FK_SubscriptionPlanFeatures_SubscriptionPlans_SubscriptionPlan~" FOREIGN KEY ("SubscriptionPlanId") REFERENCES "SubscriptionPlans" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PasswordResetTokens" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Token" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UsedAt" timestamp with time zone,
    CONSTRAINT "PK_PasswordResetTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PasswordResetTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PhoneNumber" (
    "Id" uuid NOT NULL,
    "Number" character varying(20) NOT NULL,
    "Type" character varying(50) NOT NULL,
    "IsPrimary" boolean NOT NULL,
    "IsVerified" boolean NOT NULL,
    "Notes" character varying(500),
    "ContactId" uuid,
    "UserId" uuid,
    "ContactId1" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedById" uuid,
    "UpdatedById" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedById" uuid,
    "RowVersion" bytea NOT NULL,
    CONSTRAINT "PK_PhoneNumber" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PhoneNumber_Contacts_ContactId" FOREIGN KEY ("ContactId") REFERENCES "Contacts" ("Id"),
    CONSTRAINT "FK_PhoneNumber_Contacts_ContactId1" FOREIGN KEY ("ContactId1") REFERENCES "Contacts" ("Id"),
    CONSTRAINT "FK_PhoneNumber_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "ResourceRecommendations" (
    "Id" uuid NOT NULL,
    "ContactId" uuid NOT NULL,
    "ServiceContactId" uuid NOT NULL,
    "RecommendedByUserId" uuid NOT NULL,
    "OrganizationId" uuid NOT NULL,
    "InteractionId" uuid,
    "Purpose" character varying(500) NOT NULL,
    "RecommendationOrder" integer NOT NULL,
    "RecommendationNotes" character varying(1000),
    "RecommendedAt" timestamp with time zone NOT NULL,
    "WasSelected" boolean NOT NULL,
    "WasContacted" boolean NOT NULL,
    "ContactedAt" timestamp with time zone,
    "SelectedAt" timestamp with time zone,
    "AlternativeProviderName" character varying(200),
    "AlternativeProviderContact" character varying(500),
    "WhyAlternativeChosen" character varying(1000),
    "ClientFeedback" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CustomFields" jsonb,
    CONSTRAINT "PK_ResourceRecommendations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ResourceRecommendations_Contacts_ContactId" FOREIGN KEY ("ContactId") REFERENCES "Contacts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ResourceRecommendations_Contacts_ServiceContactId" FOREIGN KEY ("ServiceContactId") REFERENCES "Contacts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ResourceRecommendations_Interactions_InteractionId" FOREIGN KEY ("InteractionId") REFERENCES "Interactions" ("Id"),
    CONSTRAINT "FK_ResourceRecommendations_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ResourceRecommendations_Users_RecommendedByUserId" FOREIGN KEY ("RecommendedByUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskItems" (
    "Id" uuid NOT NULL,
    "ContactId" uuid NOT NULL,
    "InteractionId" uuid,
    "Title" character varying(200) NOT NULL,
    "Description" text,
    "Status" character varying(32) NOT NULL DEFAULT 'pending',
    "Priority" character varying(32) NOT NULL DEFAULT 'normal',
    "AssignedToUserId" uuid,
    "DueDate" timestamp with time zone,
    "CompletedAt" timestamp with time zone,
    "RecurrenceRule" text,
    "ParentTaskId" uuid,
    "Source" character varying(32),
    "SourceReferenceId" character varying(128),
    "ConfidenceScore" double precision,
    "RequiresApproval" boolean NOT NULL,
    "ApprovalStatus" character varying(32),
    "Metadata" jsonb,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedById" uuid,
    "UpdatedById" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedById" uuid,
    "RowVersion" bytea NOT NULL,
    CONSTRAINT "PK_TaskItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskItems_Contacts_ContactId" FOREIGN KEY ("ContactId") REFERENCES "Contacts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskItems_Interactions_InteractionId" FOREIGN KEY ("InteractionId") REFERENCES "Interactions" ("Id"),
    CONSTRAINT "FK_TaskItems_TaskItems_ParentTaskId" FOREIGN KEY ("ParentTaskId") REFERENCES "TaskItems" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TaskItems_Users_AssignedToUserId" FOREIGN KEY ("AssignedToUserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "UserPhoneNumbers" (
    "Id" uuid NOT NULL,
    "Number" text NOT NULL,
    "UserId" uuid NOT NULL,
    "Label" text,
    "IsPrimary" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "VerifiedAt" timestamp with time zone,
    CONSTRAINT "PK_UserPhoneNumbers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserPhoneNumbers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Subscriptions" (
    "UserId" uuid NOT NULL,
    "StripeSubscriptionId" character varying(100),
    "PlanId" uuid NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone,
    "Status" integer NOT NULL,
    "SeatsLimit" integer NOT NULL,
    "IsCallProcessingEnabled" boolean NOT NULL,
    "OrganizationSubscriptionId" uuid,
    "SubscriptionPlanId" uuid,
    "Id" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedById" uuid,
    "UpdatedById" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedById" uuid,
    "RowVersion" bytea NOT NULL,
    CONSTRAINT "PK_Subscriptions" PRIMARY KEY ("UserId"),
    CONSTRAINT "FK_Subscriptions_OrganizationSubscription_OrganizationSubscrip~" FOREIGN KEY ("OrganizationSubscriptionId") REFERENCES "OrganizationSubscription" ("Id"),
    CONSTRAINT "FK_Subscriptions_SubscriptionPlans_PlanId" FOREIGN KEY ("PlanId") REFERENCES "SubscriptionPlans" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Subscriptions_SubscriptionPlans_SubscriptionPlanId" FOREIGN KEY ("SubscriptionPlanId") REFERENCES "SubscriptionPlans" ("Id"),
    CONSTRAINT "FK_Subscriptions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserSubscriptionAssignments" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "OrganizationSubscriptionId" uuid NOT NULL,
    "AssignedAt" timestamp with time zone NOT NULL,
    "AssignedByUserId" uuid,
    "SubscriptionId" uuid NOT NULL,
    "StartDate" timestamp with time zone,
    "EndDate" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    "DeactivatedAt" timestamp with time zone,
    "DeactivationReason" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedById" uuid,
    "UpdatedById" uuid,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "DeletedById" uuid,
    "RowVersion" bytea NOT NULL,
    CONSTRAINT "PK_UserSubscriptionAssignments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserSubscriptionAssignments_OrganizationSubscription_Organi~" FOREIGN KEY ("OrganizationSubscriptionId") REFERENCES "OrganizationSubscription" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserSubscriptionAssignments_Subscriptions_SubscriptionId" FOREIGN KEY ("SubscriptionId") REFERENCES "Subscriptions" ("UserId") ON DELETE CASCADE,
    CONSTRAINT "FK_UserSubscriptionAssignments_Users_AssignedByUserId" FOREIGN KEY ("AssignedByUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_UserSubscriptionAssignments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AccessAuditLogs_AccessedAt" ON "AccessAuditLogs" ("AccessedAt");

CREATE INDEX "IX_AccessAuditLogs_ContactId" ON "AccessAuditLogs" ("ContactId");

CREATE INDEX "IX_AccessAuditLogs_OrganizationId" ON "AccessAuditLogs" ("OrganizationId");

CREATE INDEX "IX_AccessAuditLogs_RequestingUserId" ON "AccessAuditLogs" ("RequestingUserId");

CREATE INDEX "IX_AccessAuditLogs_ResourceType" ON "AccessAuditLogs" ("ResourceType");

CREATE INDEX "IX_AccessAuditLogs_UserId" ON "AccessAuditLogs" ("UserId");

CREATE INDEX "IX_ActionItem_InteractionId" ON "ActionItem" ("InteractionId");

CREATE UNIQUE INDEX "IX_Address_ContactId" ON "Address" ("ContactId");

CREATE INDEX "IX_Address_OrganizationId" ON "Address" ("OrganizationId");

CREATE INDEX "IX_AgentAssignments_AgentId" ON "AgentAssignments" ("AgentId");

CREATE INDEX "IX_AgentAssignments_EmmaAnalysisId" ON "AgentAssignments" ("EmmaAnalysisId");

CREATE INDEX "IX_AgentPhoneNumbers_AgentId" ON "AgentPhoneNumbers" ("AgentId");

CREATE INDEX "IX_AgentPhoneNumbers_PhoneNumber" ON "AgentPhoneNumbers" ("PhoneNumber");

CREATE INDEX "IX_Agents_CreatedById" ON "Agents" ("CreatedById");

CREATE INDEX "IX_Agents_OrganizationId" ON "Agents" ("OrganizationId");

CREATE INDEX "IX_Agents_SubscriptionUserId" ON "Agents" ("SubscriptionUserId");

CREATE INDEX "IX_Attachment_InteractionId" ON "Attachment" ("InteractionId");

CREATE INDEX "IX_ContactAssignments_AssignedByUserId" ON "ContactAssignments" ("AssignedByUserId");

CREATE INDEX "IX_ContactAssignments_ContactId" ON "ContactAssignments" ("ContactId");

CREATE INDEX "IX_ContactAssignments_InteractionId" ON "ContactAssignments" ("InteractionId");

CREATE INDEX "IX_ContactAssignments_OrganizationId" ON "ContactAssignments" ("OrganizationId");

CREATE INDEX "IX_ContactAssignments_ServiceContactId" ON "ContactAssignments" ("ServiceContactId");

CREATE INDEX "IX_ContactCollaborators_CollaboratorUserId" ON "ContactCollaborators" ("CollaboratorUserId");

CREATE INDEX "IX_ContactCollaborators_ContactId" ON "ContactCollaborators" ("ContactId");

CREATE INDEX "IX_ContactCollaborators_ContactId1" ON "ContactCollaborators" ("ContactId1");

CREATE INDEX "IX_ContactCollaborators_GrantedByUserId" ON "ContactCollaborators" ("GrantedByUserId");

CREATE INDEX "IX_ContactCollaborators_OrganizationId" ON "ContactCollaborators" ("OrganizationId");

CREATE INDEX "IX_Contacts_AgentId" ON "Contacts" ("AgentId");

CREATE INDEX "IX_Contacts_AssignedToId" ON "Contacts" ("AssignedToId");

CREATE INDEX "IX_Contacts_OrganizationId" ON "Contacts" ("OrganizationId");

CREATE INDEX "IX_Contacts_OwnerId" ON "Contacts" ("OwnerId");

CREATE INDEX "IX_ContactStateHistory_ChangedByUserId" ON "ContactStateHistory" ("ChangedByUserId");

CREATE INDEX "IX_ContactStateHistory_ContactId" ON "ContactStateHistory" ("ContactId");

CREATE INDEX "IX_ContactStates_AssignedUserId" ON "ContactStates" ("AssignedUserId");

CREATE UNIQUE INDEX "IX_ContactStates_ContactId_OrganizationId" ON "ContactStates" ("ContactId", "OrganizationId");

CREATE INDEX "IX_ContactSummaries_ContactId_OrganizationId_SummaryType" ON "ContactSummaries" ("ContactId", "OrganizationId", "SummaryType");

CREATE UNIQUE INDEX "IX_ConversationSummaries_InteractionId" ON "ConversationSummaries" ("InteractionId");

CREATE INDEX "IX_ConversationSummaries_QualityScore" ON "ConversationSummaries" ("QualityScore");

CREATE INDEX "IX_DetailedNotes_InteractionId" ON "DetailedNotes" ("InteractionId");

CREATE UNIQUE INDEX "IX_EmailAddresses_Address_Unique" ON "EmailAddresses" ("Address");

CREATE INDEX "IX_EmailAddresses_ContactId" ON "EmailAddresses" ("ContactId");

CREATE INDEX "IX_EmailAddresses_ContactId1" ON "EmailAddresses" ("ContactId1");

CREATE INDEX "IX_EmailAddresses_UserId" ON "EmailAddresses" ("UserId");

CREATE INDEX "IX_EmmaAnalyses_MessageId" ON "EmmaAnalyses" ("MessageId");

CREATE INDEX "IX_EmmaTask_EmmaAnalysisId" ON "EmmaTask" ("EmmaAnalysisId");

CREATE INDEX "IX_InteractionEmbeddings_ContactId_OrganizationId_Timestamp" ON "InteractionEmbeddings" ("ContactId", "OrganizationId", "Timestamp");

CREATE UNIQUE INDEX "IX_InteractionEmbeddings_InteractionId" ON "InteractionEmbeddings" ("InteractionId");

CREATE INDEX "IX_Interactions_AgentId" ON "Interactions" ("AgentId");

CREATE UNIQUE INDEX "IX_Interactions_ContactId" ON "Interactions" ("ContactId");

CREATE INDEX "IX_Interactions_CreatedById" ON "Interactions" ("CreatedById");

CREATE INDEX "IX_Interactions_OrganizationId" ON "Interactions" ("OrganizationId");

CREATE INDEX "IX_Interactions_ParentInteractionId" ON "Interactions" ("ParentInteractionId");

CREATE INDEX "IX_InteractionTranscriptions_InteractionId" ON "InteractionTranscriptions" ("InteractionId");

CREATE INDEX "IX_InteractionTranscriptions_TranscriptionId" ON "InteractionTranscriptions" ("TranscriptionId");

CREATE INDEX "IX_Messages_AgentId" ON "Messages" ("AgentId");

CREATE INDEX "IX_Messages_InteractionId" ON "Messages" ("InteractionId");

CREATE UNIQUE INDEX "IX_Messages_OccurredAt_Type" ON "Messages" ("OccurredAt", "Type");

CREATE INDEX "IX_Messages_UserId" ON "Messages" ("UserId");

CREATE UNIQUE INDEX "IX_Organizations_Email" ON "Organizations" ("Email");

CREATE UNIQUE INDEX "IX_Organizations_FubApiKey" ON "Organizations" ("FubApiKey");

CREATE UNIQUE INDEX "IX_Organizations_FubSystem" ON "Organizations" ("FubSystem");

CREATE UNIQUE INDEX "IX_Organizations_FubSystemKey" ON "Organizations" ("FubSystemKey");

CREATE INDEX "IX_Organizations_OwnerUserId" ON "Organizations" ("OwnerUserId");

CREATE INDEX "IX_OrganizationSubscription_OrganizationId" ON "OrganizationSubscription" ("OrganizationId");

CREATE INDEX "IX_OrganizationSubscription_SubscriptionPlanId" ON "OrganizationSubscription" ("SubscriptionPlanId");

CREATE INDEX "IX_PasswordResetTokens_UserId" ON "PasswordResetTokens" ("UserId");

CREATE INDEX "IX_PhoneNumber_ContactId" ON "PhoneNumber" ("ContactId");

CREATE INDEX "IX_PhoneNumber_ContactId1" ON "PhoneNumber" ("ContactId1");

CREATE INDEX "IX_PhoneNumber_UserId" ON "PhoneNumber" ("UserId");

CREATE INDEX "IX_RelatedEntity_InteractionId" ON "RelatedEntity" ("InteractionId");

CREATE INDEX "IX_ResourceRecommendations_ContactId" ON "ResourceRecommendations" ("ContactId");

CREATE INDEX "IX_ResourceRecommendations_InteractionId" ON "ResourceRecommendations" ("InteractionId");

CREATE INDEX "IX_ResourceRecommendations_OrganizationId" ON "ResourceRecommendations" ("OrganizationId");

CREATE INDEX "IX_ResourceRecommendations_RecommendedByUserId" ON "ResourceRecommendations" ("RecommendedByUserId");

CREATE INDEX "IX_ResourceRecommendations_ServiceContactId" ON "ResourceRecommendations" ("ServiceContactId");

CREATE INDEX "IX_SubscriptionPlanFeatures_FeatureId" ON "SubscriptionPlanFeatures" ("FeatureId");

CREATE INDEX "IX_SubscriptionPlanFeatures_FeatureId1" ON "SubscriptionPlanFeatures" ("FeatureId1");

CREATE INDEX "IX_SubscriptionPlans_OrganizationId" ON "SubscriptionPlans" ("OrganizationId");

CREATE INDEX "IX_Subscriptions_OrganizationSubscriptionId" ON "Subscriptions" ("OrganizationSubscriptionId");

CREATE INDEX "IX_Subscriptions_PlanId" ON "Subscriptions" ("PlanId");

CREATE INDEX "IX_Subscriptions_SubscriptionPlanId" ON "Subscriptions" ("SubscriptionPlanId");

CREATE INDEX "IX_SummaryOfSummaries_ContactId" ON "SummaryOfSummaries" ("ContactId");

CREATE INDEX "IX_SummaryOfSummaries_InteractionId" ON "SummaryOfSummaries" ("InteractionId");

CREATE INDEX "IX_TaskItems_AssignedToUserId" ON "TaskItems" ("AssignedToUserId");

CREATE INDEX "IX_TaskItems_ContactId" ON "TaskItems" ("ContactId");

CREATE INDEX "IX_TaskItems_DueDate" ON "TaskItems" ("DueDate");

CREATE INDEX "IX_TaskItems_InteractionId" ON "TaskItems" ("InteractionId");

CREATE INDEX "IX_TaskItems_ParentTaskId" ON "TaskItems" ("ParentTaskId");

CREATE INDEX "IX_TaskItems_Priority" ON "TaskItems" ("Priority");

CREATE INDEX "IX_TaskItems_Status" ON "TaskItems" ("Status");

CREATE UNIQUE INDEX "IX_Transcriptions_MessageId" ON "Transcriptions" ("MessageId");

CREATE INDEX "IX_UserPhoneNumbers_UserId" ON "UserPhoneNumbers" ("UserId");

CREATE INDEX "IX_Users_OrganizationId" ON "Users" ("OrganizationId");

CREATE INDEX "IX_UserSubscriptionAssignments_AssignedByUserId" ON "UserSubscriptionAssignments" ("AssignedByUserId");

CREATE INDEX "IX_UserSubscriptionAssignments_OrganizationSubscriptionId" ON "UserSubscriptionAssignments" ("OrganizationSubscriptionId");

CREATE INDEX "IX_UserSubscriptionAssignments_SubscriptionId" ON "UserSubscriptionAssignments" ("SubscriptionId");

CREATE INDEX "IX_UserSubscriptionAssignments_UserId" ON "UserSubscriptionAssignments" ("UserId");

ALTER TABLE "AccessAuditLogs" ADD CONSTRAINT "FK_AccessAuditLogs_Contacts_ContactId" FOREIGN KEY ("ContactId") REFERENCES "Contacts" ("Id") ON DELETE RESTRICT;

ALTER TABLE "AccessAuditLogs" ADD CONSTRAINT "FK_AccessAuditLogs_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT;

ALTER TABLE "AccessAuditLogs" ADD CONSTRAINT "FK_AccessAuditLogs_Users_RequestingUserId" FOREIGN KEY ("RequestingUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;

ALTER TABLE "AccessAuditLogs" ADD CONSTRAINT "FK_AccessAuditLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id");

ALTER TABLE "ActionItem" ADD CONSTRAINT "FK_ActionItem_Interactions_InteractionId" FOREIGN KEY ("InteractionId") REFERENCES "Interactions" ("Id");

ALTER TABLE "Address" ADD CONSTRAINT "FK_Address_Contacts_ContactId" FOREIGN KEY ("ContactId") REFERENCES "Contacts" ("Id");

ALTER TABLE "Address" ADD CONSTRAINT "FK_Address_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id");

ALTER TABLE "AgentAssignments" ADD CONSTRAINT "FK_AgentAssignments_Agents_AgentId" FOREIGN KEY ("AgentId") REFERENCES "Agents" ("Id") ON DELETE CASCADE;

ALTER TABLE "AgentAssignments" ADD CONSTRAINT "FK_AgentAssignments_EmmaAnalyses_EmmaAnalysisId" FOREIGN KEY ("EmmaAnalysisId") REFERENCES "EmmaAnalyses" ("Id") ON DELETE CASCADE;

ALTER TABLE "Agents" ADD CONSTRAINT "FK_Agents_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Agents" ADD CONSTRAINT "FK_Agents_Subscriptions_SubscriptionUserId" FOREIGN KEY ("SubscriptionUserId") REFERENCES "Subscriptions" ("UserId");

ALTER TABLE "Agents" ADD CONSTRAINT "FK_Agents_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id");

ALTER TABLE "Attachment" ADD CONSTRAINT "FK_Attachment_Interactions_InteractionId" FOREIGN KEY ("InteractionId") REFERENCES "Interactions" ("Id");

ALTER TABLE "CallMetadata" ADD CONSTRAINT "FK_CallMetadata_Messages_MessageId" FOREIGN KEY ("MessageId") REFERENCES "Messages" ("Id") ON DELETE CASCADE;

ALTER TABLE "ContactAssignments" ADD CONSTRAINT "FK_ContactAssignments_Contacts_ContactId" FOREIGN KEY ("ContactId") REFERENCES "Contacts" ("Id") ON DELETE RESTRICT;

ALTER TABLE "ContactAssignments" ADD CONSTRAINT "FK_ContactAssignments_Contacts_ServiceContactId" FOREIGN KEY ("ServiceContactId") REFERENCES "Contacts" ("Id") ON DELETE CASCADE;

ALTER TABLE "ContactAssignments" ADD CONSTRAINT "FK_ContactAssignments_Interactions_InteractionId" FOREIGN KEY ("InteractionId") REFERENCES "Interactions" ("Id");

ALTER TABLE "ContactAssignments" ADD CONSTRAINT "FK_ContactAssignments_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE;

ALTER TABLE "ContactAssignments" ADD CONSTRAINT "FK_ContactAssignments_Users_AssignedByUserId" FOREIGN KEY ("AssignedByUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE;

ALTER TABLE "ContactCollaborators" ADD CONSTRAINT "FK_ContactCollaborators_Contacts_ContactId" FOREIGN KEY ("ContactId") REFERENCES "Contacts" ("Id") ON DELETE RESTRICT;

ALTER TABLE "ContactCollaborators" ADD CONSTRAINT "FK_ContactCollaborators_Contacts_ContactId1" FOREIGN KEY ("ContactId1") REFERENCES "Contacts" ("Id");

ALTER TABLE "ContactCollaborators" ADD CONSTRAINT "FK_ContactCollaborators_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE;

ALTER TABLE "ContactCollaborators" ADD CONSTRAINT "FK_ContactCollaborators_Users_CollaboratorUserId" FOREIGN KEY ("CollaboratorUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE;

ALTER TABLE "ContactCollaborators" ADD CONSTRAINT "FK_ContactCollaborators_Users_GrantedByUserId" FOREIGN KEY ("GrantedByUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE;

ALTER TABLE "Contacts" ADD CONSTRAINT "FK_Contacts_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE;

ALTER TABLE "Contacts" ADD CONSTRAINT "FK_Contacts_Users_AssignedToId" FOREIGN KEY ("AssignedToId") REFERENCES "Users" ("Id");

ALTER TABLE "Contacts" ADD CONSTRAINT "FK_Contacts_Users_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES "Users" ("Id");

ALTER TABLE "ContactStateHistory" ADD CONSTRAINT "FK_ContactStateHistory_Users_ChangedByUserId" FOREIGN KEY ("ChangedByUserId") REFERENCES "Users" ("Id");

ALTER TABLE "ContactStates" ADD CONSTRAINT "FK_ContactStates_Users_AssignedUserId" FOREIGN KEY ("AssignedUserId") REFERENCES "Users" ("Id");

ALTER TABLE "ConversationSummaries" ADD CONSTRAINT "FK_ConversationSummaries_Interactions_InteractionId" FOREIGN KEY ("InteractionId") REFERENCES "Interactions" ("Id") ON DELETE CASCADE;

ALTER TABLE "DetailedNotes" ADD CONSTRAINT "FK_DetailedNotes_Interactions_InteractionId" FOREIGN KEY ("InteractionId") REFERENCES "Interactions" ("Id") ON DELETE CASCADE;

ALTER TABLE "DeviceTokens" ADD CONSTRAINT "FK_DeviceTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE;

ALTER TABLE "EmailAddresses" ADD CONSTRAINT "FK_EmailAddresses_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id");

ALTER TABLE "EmmaAnalyses" ADD CONSTRAINT "FK_EmmaAnalyses_Messages_MessageId" FOREIGN KEY ("MessageId") REFERENCES "Messages" ("Id") ON DELETE CASCADE;

ALTER TABLE "InteractionEmbeddings" ADD CONSTRAINT "FK_InteractionEmbeddings_Interactions_InteractionId" FOREIGN KEY ("InteractionId") REFERENCES "Interactions" ("Id") ON DELETE CASCADE;

ALTER TABLE "Interactions" ADD CONSTRAINT "FK_Interactions_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE;

ALTER TABLE "Interactions" ADD CONSTRAINT "FK_Interactions_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE CASCADE;

ALTER TABLE "InteractionTranscriptions" ADD CONSTRAINT "FK_InteractionTranscriptions_Transcriptions_TranscriptionId" FOREIGN KEY ("TranscriptionId") REFERENCES "Transcriptions" ("Id") ON DELETE CASCADE;

ALTER TABLE "Messages" ADD CONSTRAINT "FK_Messages_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE;

ALTER TABLE "Organizations" ADD CONSTRAINT "FK_Organizations_Users_OwnerUserId" FOREIGN KEY ("OwnerUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250702174253_InitialCreate', '8.0.5');

COMMIT;