// Global using directives for test projects
global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Net;
global using System.Net.Http;
global using System.Text;
global using System.Text.Json;
global using System.Threading;
global using System.Threading.Tasks;
global using Azure;
global using Azure.AI.OpenAI;
global using Azure.Core;
global using Emma.Api.Services;
global using Emma.Core.Config;
global using Emma.Core.Dtos;
global using Emma.Core.Models;
global using Microsoft.AspNetCore.Http;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Moq;
global using Xunit;
global using Xunit.Abstractions;
global using static Emma.Api.IntegrationTests.TestHelpers.TestHelper;
