CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "Features" (
        "Id" uuid NOT NULL,
        "Code" character varying(100) NOT NULL,
        "DisplayName" character varying(200) NOT NULL,
        "Description" character varying(1000),
        "Category" character varying(100),
        "IsActive" boolean NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedById" uuid,
        "UpdatedById" uuid,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "DeletedById" uuid,
        "RowVersion" bytea NOT NULL,
        CONSTRAINT "PK_Features" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE test_entities (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(500),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_test_entities" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "AccessAuditLogs" (
        "Id" uuid NOT NULL,
        "UserId" uuid,
        "RequestingUserId" uuid NOT NULL,
        "OrganizationId" uuid NOT NULL,
        "Action" character varying(50) NOT NULL,
        "EntityType" character varying(100) NOT NULL,
        "EntityId" uuid NOT NULL,
        "ResourceType" character varying(50) NOT NULL,
        "ResourceId" uuid NOT NULL,
        "ContactId" uuid,
        "AccessGranted" boolean NOT NULL,
        "Timestamp" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "IpAddress" character varying(45),
        "UserAgent" character varying(500),
        "Reason" character varying(500) NOT NULL,
        "PrivacyTags" character varying(1000) NOT NULL,
        "Metadata" character varying(2000),
        "AccessedAt" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedById" uuid,
        "UpdatedById" uuid,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "DeletedById" uuid,
        "RowVersion" bytea NOT NULL,
        CONSTRAINT "PK_AccessAuditLogs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "ActionItem" (
        "Id" text NOT NULL,
        "Text" text NOT NULL,
        "Status" character varying(50) NOT NULL,
        "Type" text NOT NULL,
        "Priority" character varying(20),
        "AssignedTo" uuid,
        "DueBy" timestamp with time zone,
        "CompletedAt" timestamp with time zone,
        "InteractionId" uuid,
        CONSTRAINT "PK_ActionItem" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "AgentAssignment" (
        "Id" uuid NOT NULL,
        "EmmaAnalysisId" uuid NOT NULL,
        "AgentId" uuid NOT NULL,
        "AssignmentType" text NOT NULL,
        "AssignedAt" timestamp with time zone NOT NULL,
        "Analysis" text,
        CONSTRAINT "PK_AgentAssignment" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "Agents" (
        "Id" uuid NOT NULL,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(500),
        "AgentType" character varying(50) NOT NULL,
        "Configuration" character varying(4000),
        "IsActive" boolean NOT NULL,
        "Status" character varying(20) NOT NULL DEFAULT 'Active',
        "LastHeartbeat" timestamp with time zone,
        "Capabilities" text NOT NULL,
        "Metadata" jsonb,
        "Version" character varying(50),
        "CreatedAt" timestamp with time zone NOT NULL,
        "LastActive" timestamp with time zone,
        "OrganizationId" uuid,
        "CreatedById" uuid,
        "SubscriptionId" uuid,
        CONSTRAINT "PK_Agents" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "Attachment" (
        "Id" text NOT NULL,
        "Name" text NOT NULL,
        "Type" text NOT NULL,
        "Size" bigint NOT NULL,
        "Url" text,
        "PreviewUrl" text,
        "InteractionId" uuid,
        CONSTRAINT "PK_Attachment" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "CallMetadata" (
        "MessageId" uuid NOT NULL,
        "ClientPhoneNumber" text NOT NULL,
        "DurationInSeconds" integer NOT NULL,
        "DirectionBasedOnAgent" integer NOT NULL,
        "Status" integer NOT NULL,
        "ReferenceId" text NOT NULL,
        CONSTRAINT "PK_CallMetadata" PRIMARY KEY ("MessageId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "ContactAssignments" (
        "Id" uuid NOT NULL,
        "ContactId" uuid NOT NULL,
        "ServiceContactId" uuid NOT NULL,
        "AssignedByUserId" uuid NOT NULL,
        "OrganizationId" uuid NOT NULL,
        "Purpose" character varying(500) NOT NULL,
        "Status" integer NOT NULL,
        "Priority" integer NOT NULL,
        "InteractionId" uuid,
        "ClientRequest" character varying(1000),
        "AssignedAt" timestamp with time zone NOT NULL,
        "CompletedAt" timestamp with time zone,
        "FollowUpAt" timestamp with time zone,
        "WasUsed" boolean NOT NULL,
        "ClientRating" numeric,
        "ClientFeedback" character varying(1000),
        "OutcomeNotes" character varying(1000),
        "InternalNotes" character varying(1000),
        "ReferralDisclosureProvided" boolean NOT NULL,
        "ReferralDisclosureDate" timestamp with time zone,
        "LiabilityDisclaimerAcknowledged" boolean NOT NULL,
        "LiabilityDisclaimerDate" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "CustomFields" jsonb,
        CONSTRAINT "PK_ContactAssignments" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "ContactCollaborators" (
        "Id" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "ContactId" uuid NOT NULL,
        "CollaboratorUserId" uuid NOT NULL,
        "GrantedByUserId" uuid NOT NULL,
        "OrganizationId" uuid NOT NULL,
        "Role" integer NOT NULL,
        "CanAccessBusinessInteractions" boolean NOT NULL,
        "CanAccessPersonalInteractions" boolean NOT NULL,
        "CanCreateInteractions" boolean NOT NULL,
        "CanEditInteractions" boolean NOT NULL,
        "CanAssignResources" boolean NOT NULL,
        "CanAccessFinancialData" boolean NOT NULL,
        "CanEditContactDetails" boolean NOT NULL,
        "CanManageCollaborators" boolean NOT NULL,
        "CanViewAuditLogs" boolean NOT NULL,
        "Reason" character varying(500),
        "ExpiresAt" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_ContactCollaborators" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "Contacts" (
        "Id" uuid NOT NULL,
        "OrganizationId" uuid NOT NULL,
        "FirstName" character varying(100) NOT NULL,
        "LastName" character varying(100) NOT NULL,
        "MiddleName" character varying(100),
        "PreferredName" character varying(100),
        "Title" character varying(50),
        "JobTitle" character varying(200),
        "Company" character varying(200),
        "Department" character varying(200),
        "RelationshipState" integer NOT NULL,
        "LastContactedAt" timestamp with time zone,
        "NextFollowUpAt" timestamp with time zone,
        "Source" character varying(100),
        "OwnerId" uuid,
        "PreferredContactMethod" character varying(50),
        "PreferredContactTime" character varying(50),
        "Notes" text,
        "ProfilePictureUrl" character varying(500),
        "IsActiveClient" boolean NOT NULL,
        "ClientSince" timestamp with time zone,
        "CompanyName" text,
        "LicenseNumber" text,
        "Rating" numeric,
        "ReviewCount" integer NOT NULL,
        "IsPreferred" boolean NOT NULL,
        "Website" text,
        "LeadSource" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "PhoneNumbers" jsonb NOT NULL DEFAULT ('[]'::jsonb),
        "ServiceAreas" text[] NOT NULL DEFAULT ('{}'::text[]),
        "Specialties" text[] NOT NULL DEFAULT ('{}'::text[]),
        "Tags" jsonb NOT NULL DEFAULT ('[]'::jsonb),
        "CreatedById" uuid,
        "UpdatedById" uuid,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "DeletedById" uuid,
        "RowVersion" bytea NOT NULL,
        CONSTRAINT "PK_Contacts" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "ContactSummaries" (
        "Id" text NOT NULL,
        "ContactId" uuid NOT NULL,
        "OrganizationId" uuid NOT NULL,
        "SummaryType" text NOT NULL,
        "SummaryText" text NOT NULL,
        "InteractionCount" integer NOT NULL,
        "EarliestInteraction" timestamp with time zone NOT NULL,
        "LatestInteraction" timestamp with time zone NOT NULL,
        "KeyMilestones" jsonb NOT NULL,
        "ImportantPreferences" jsonb NOT NULL,
        "CustomFields" jsonb NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "LastUpdated" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ContactSummaries" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ContactSummaries_Contacts_ContactId" FOREIGN KEY ("ContactId") REFERENCES "Contacts" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "PhoneNumber" (
        "Id" uuid NOT NULL,
        "Number" character varying(20) NOT NULL,
        "Type" character varying(50) NOT NULL,
        "IsPrimary" boolean NOT NULL,
        "IsVerified" boolean NOT NULL,
        "VerifiedAt" timestamp with time zone,
        "Notes" character varying(500),
        "ContactId" uuid,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedById" uuid,
        "UpdatedById" uuid,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "DeletedById" uuid,
        "RowVersion" bytea NOT NULL,
        CONSTRAINT "PK_PhoneNumber" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PhoneNumber_Contacts_ContactId" FOREIGN KEY ("ContactId") REFERENCES "Contacts" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "ContactStateHistories" (
        "Id" uuid NOT NULL,
        "ContactId" uuid NOT NULL,
        "FromState" character varying(20) NOT NULL,
        "ToState" character varying(20) NOT NULL,
        "TransitionDate" timestamp with time zone NOT NULL,
        "Reason" character varying(1000),
        "ChangedByUserId" uuid,
        "Metadata" jsonb,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedById" uuid,
        "UpdatedById" uuid,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "DeletedById" uuid,
        "RowVersion" bytea NOT NULL,
        CONSTRAINT "PK_ContactStateHistories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ContactStateHistories_Contacts_ContactId" FOREIGN KEY ("ContactId") REFERENCES "Contacts" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "ContactStates" (
        "Id" text NOT NULL,
        "ContactId" uuid NOT NULL,
        "OrganizationId" uuid NOT NULL,
        "CurrentStage" text NOT NULL,
        "NextMilestone" text,
        "Priority" text NOT NULL,
        "AssignedUserId" uuid,
        "PendingTasks" jsonb NOT NULL,
        "OpenObjections" jsonb NOT NULL,
        "ImportantDates" jsonb NOT NULL,
        "PropertyInfo" jsonb NOT NULL,
        "FinancialInfo" jsonb NOT NULL,
        "CustomFields" jsonb NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "LastUpdated" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ContactStates" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ContactStates_Contacts_ContactId" FOREIGN KEY ("ContactId") REFERENCES "Contacts" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "DeviceTokens" (
        "UserId" uuid NOT NULL,
        "DeviceId" character varying(255) NOT NULL,
        "Token" character varying(500) NOT NULL,
        "Platform" character varying(50) NOT NULL,
        "DeviceName" character varying(100),
        "DeviceModel" character varying(100),
        "OsVersion" character varying(50),
        "AppVersion" character varying(50),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "LastUsedAt" timestamp with time zone,
        "Id" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedById" uuid,
        "UpdatedById" uuid,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "DeletedById" uuid,
        "RowVersion" bytea NOT NULL,
        CONSTRAINT "PK_DeviceTokens" PRIMARY KEY ("UserId", "DeviceId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "EmailAddresses" (
        "Id" uuid NOT NULL,
        "Address" character varying(255) NOT NULL,
        "IsPrimary" boolean NOT NULL,
        "Verified" boolean DEFAULT FALSE,
        "Type" character varying(50),
        "UserId" uuid,
        "ContactId" uuid,
        "ContactId1" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedById" uuid,
        "UpdatedById" uuid,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "DeletedById" uuid,
        "RowVersion" bytea NOT NULL,
        CONSTRAINT "PK_EmailAddresses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_EmailAddresses_Contacts_ContactId" FOREIGN KEY ("ContactId") REFERENCES "Contacts" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_EmailAddresses_Contacts_ContactId1" FOREIGN KEY ("ContactId1") REFERENCES "Contacts" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "EmmaAnalyses" (
        "Id" uuid NOT NULL,
        "MessageId" uuid NOT NULL,
        "LeadStatus" character varying(50) NOT NULL,
        "RecommendedStrategy" character varying(500) NOT NULL,
        "ComplianceFlags" text NOT NULL,
        "FollowupGuidance" character varying(2000) NOT NULL,
        "ConfidenceScore" smallint,
        "ModelVersion" character varying(50),
        "Metadata" jsonb,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedById" uuid,
        "UpdatedById" uuid,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "DeletedById" uuid,
        "RowVersion" bytea NOT NULL,
        CONSTRAINT "PK_EmmaAnalyses" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "EmmaTask" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TaskType" text NOT NULL,
        "Description" text NOT NULL,
        "DueDate" timestamp with time zone NOT NULL,
        "Analysis" text,
        "EmmaAnalysisId" uuid,
        CONSTRAINT "PK_EmmaTask" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_EmmaTask_EmmaAnalyses_EmmaAnalysisId" FOREIGN KEY ("EmmaAnalysisId") REFERENCES "EmmaAnalyses" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "InteractionEmbeddings" (
        "Id" text NOT NULL,
        "ContactId" uuid NOT NULL,
        "InteractionId" uuid NOT NULL,
        "OrganizationId" uuid NOT NULL,
        "Timestamp" timestamp with time zone NOT NULL,
        "Type" text NOT NULL,
        "Summary" text NOT NULL,
        "RawContent" text,
        "EmbeddingModel" text NOT NULL,
        "ModelVersion" text NOT NULL,
        "PrivacyTags" jsonb NOT NULL,
        "ExtractedEntities" jsonb NOT NULL,
        "Topics" jsonb NOT NULL,
        "SentimentScore" double precision NOT NULL,
        "CustomFields" jsonb NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_InteractionEmbeddings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_InteractionEmbeddings_Contacts_ContactId" FOREIGN KEY ("ContactId") REFERENCES "Contacts" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "Interactions" (
        "Id" uuid NOT NULL,
        "AssignedToUserId" uuid,
        "AssignedToAgentId" uuid,
        "AssignedToId" uuid,
        "OrganizationId" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "ContactId" uuid NOT NULL,
        "ParentInteractionId" uuid,
        "ThreadId" text,
        "Version" integer NOT NULL,
        "Type" character varying(100) NOT NULL,
        "Direction" character varying(50) NOT NULL,
        "Status" character varying(50) NOT NULL,
        "Priority" character varying(20) NOT NULL,
        "Subject" character varying(500),
        "Content" text,
        "Summary" character varying(2000),
        "VectorEmbedding" real[],
        "SentimentScore" real,
        "SentimentLabel" character varying(50),
        "AiMetadata" jsonb,
        "PrivacyLevel" character varying(50) NOT NULL,
        "Confidentiality" character varying(50),
        "RetentionPolicy" character varying(100),
        "IsRead" boolean NOT NULL,
        "IsStarred" boolean NOT NULL,
        "FollowUpRequired" boolean NOT NULL,
        "Channel" character varying(100) NOT NULL,
        "ChannelData" jsonb,
        "Tags" text NOT NULL,
        "CustomFields" jsonb NOT NULL,
        "ExternalIds" text NOT NULL,
        "Metadata" text NOT NULL,
        "StartedAt" timestamp with time zone,
        "EndedAt" timestamp with time zone,
        "ScheduledFor" timestamp with time zone,
        "DurationSeconds" integer,
        "FollowUpBy" timestamp with time zone,
        "CreatedById" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "DeletedAt" timestamp with time zone,
        "AgentId" uuid,
        "OrganizationId1" uuid,
        "UpdatedById" uuid,
        "IsDeleted" boolean NOT NULL,
        "DeletedById" uuid,
        "RowVersion" bytea NOT NULL,
        CONSTRAINT "PK_Interactions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Interactions_Agents_AgentId" FOREIGN KEY ("AgentId") REFERENCES "Agents" ("Id"),
        CONSTRAINT "FK_Interactions_Agents_AssignedToAgentId" FOREIGN KEY ("AssignedToAgentId") REFERENCES "Agents" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Interactions_Contacts_ContactId" FOREIGN KEY ("ContactId") REFERENCES "Contacts" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Interactions_Interactions_ParentInteractionId" FOREIGN KEY ("ParentInteractionId") REFERENCES "Interactions" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "Participant" (
        "Id" uuid NOT NULL,
        "ContactId" uuid NOT NULL,
        "Role" text NOT NULL,
        "Name" text,
        "Email" text,
        "Phone" text,
        "InteractionId" uuid NOT NULL,
        CONSTRAINT "PK_Participant" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Participant_Interactions_InteractionId" FOREIGN KEY ("InteractionId") REFERENCES "Interactions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "RelatedEntity" (
        "Id" uuid NOT NULL,
        "Type" text NOT NULL,
        "ExternalId" text,
        "Name" text,
        "InteractionId" uuid NOT NULL,
        CONSTRAINT "PK_RelatedEntity" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RelatedEntity_Interactions_InteractionId" FOREIGN KEY ("InteractionId") REFERENCES "Interactions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "Messages" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Payload" text NOT NULL,
        "AiResponse" text,
        "BlobStorageUrl" character varying(1000),
        "Type" integer NOT NULL,
        "OccurredAt" timestamp with time zone NOT NULL,
        "InteractionId" uuid NOT NULL,
        "Direction" integer NOT NULL,
        "Status" character varying(50) NOT NULL,
        "ErrorDetails" character varying(2000),
        "Metadata" jsonb,
        "AgentId" uuid,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedById" uuid,
        "UpdatedById" uuid,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "DeletedById" uuid,
        "RowVersion" bytea NOT NULL,
        CONSTRAINT "PK_Messages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Messages_Agents_AgentId" FOREIGN KEY ("AgentId") REFERENCES "Agents" ("Id"),
        CONSTRAINT "FK_Messages_Interactions_InteractionId" FOREIGN KEY ("InteractionId") REFERENCES "Interactions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "Transcriptions" (
        "Id" uuid NOT NULL,
        "BlobStorageUrl" text NOT NULL,
        "Type" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "MessageId" uuid NOT NULL,
        CONSTRAINT "PK_Transcriptions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Transcriptions_Messages_MessageId" FOREIGN KEY ("MessageId") REFERENCES "Messages" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "OrganizationInvitations" (
        "Id" uuid NOT NULL,
        "OrganizationId" uuid NOT NULL,
        "Email" character varying(200) NOT NULL,
        "Role" character varying(50) NOT NULL,
        "Token" character varying(100) NOT NULL,
        "ExpiresAt" timestamp with time zone,
        "InvitedByUserId" uuid,
        "AcceptedAt" timestamp with time zone,
        "RevokedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedById" uuid,
        "UpdatedById" uuid,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "DeletedById" uuid,
        "RowVersion" bytea NOT NULL,
        CONSTRAINT "PK_OrganizationInvitations" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "Organizations" (
        "Id" uuid NOT NULL,
        "OrgGuid" uuid NOT NULL,
        "PlanType" integer,
        "SeatCount" integer,
        "Name" character varying(200) NOT NULL,
        "Website" character varying(255),
        "PhoneNumber" character varying(50),
        "LogoUrl" character varying(500),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "TimeZone" character varying(100),
        "Locale" character varying(20),
        "Currency" character varying(3),
        "Email" character varying(200) NOT NULL,
        "OwnerUserId" uuid NOT NULL,
        "IndustryCode" character varying(100) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "FubApiKey" character varying(100),
        "FubSystem" character varying(50),
        "FubSystemKey" character varying(100),
        "FubId" integer,
        "CreatedById" uuid,
        "UpdatedById" uuid,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "DeletedById" uuid,
        "RowVersion" bytea NOT NULL,
        CONSTRAINT "PK_Organizations" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "SubscriptionPlans" (
        "Id" uuid NOT NULL,
        "Name" character varying(100) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        "Description" character varying(500),
        "OrganizationId" uuid NOT NULL,
        "MonthlyPrice" numeric(18,2) NOT NULL,
        "AnnualPrice" numeric(18,2),
        "MaxUsers" integer,
        "MaxContacts" integer,
        "MaxStorageMb" bigint,
        "CreatedById" uuid,
        "UpdatedById" uuid,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "DeletedById" uuid,
        "RowVersion" bytea NOT NULL,
        CONSTRAINT "PK_SubscriptionPlans" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SubscriptionPlans_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "Users" (
        "Id" uuid NOT NULL,
        "Roles" text[] NOT NULL,
        "ProfileImageUrl" character varying(500),
        "TimeZone" character varying(100),
        "Locale" character varying(10),
        "LastLoginAt" timestamp with time zone,
        "FirstName" character varying(100) NOT NULL,
        "LastName" character varying(100) NOT NULL,
        "Email" character varying(255) NOT NULL,
        "Password" character varying(255) NOT NULL,
        "FubApiKey" character varying(255),
        "FubUserId" integer,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "AccountStatus" integer NOT NULL,
        "VerificationToken" character varying(200),
        "IsVerified" boolean NOT NULL,
        "IsAdmin" boolean NOT NULL,
        "Role" character varying(50),
        "OrganizationId" uuid,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedById" uuid,
        "UpdatedById" uuid,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "DeletedById" uuid,
        "RowVersion" bytea NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Users_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "OrganizationSubscription" (
        "Id" uuid NOT NULL,
        "OrganizationId" uuid NOT NULL,
        "SubscriptionPlanId" uuid NOT NULL,
        "SeatsLimit" integer NOT NULL,
        "StripeSubscriptionId" character varying(100),
        "StartDate" timestamp with time zone NOT NULL,
        "EndDate" timestamp with time zone,
        "Status" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedById" uuid,
        "UpdatedById" uuid,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "DeletedById" uuid,
        "RowVersion" bytea NOT NULL,
        CONSTRAINT "PK_OrganizationSubscription" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OrganizationSubscription_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_OrganizationSubscription_SubscriptionPlans_SubscriptionPlan~" FOREIGN KEY ("SubscriptionPlanId") REFERENCES "SubscriptionPlans" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "SubscriptionPlanFeatures" (
        "Id" uuid NOT NULL,
        "SubscriptionPlanId" uuid NOT NULL,
        "FeatureId" uuid NOT NULL,
        "AddedAt" timestamp with time zone NOT NULL,
        "IsEnabled" boolean NOT NULL,
        "Limit" integer,
        "Notes" character varying(500),
        "FeatureId1" uuid,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedById" uuid,
        "UpdatedById" uuid,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "DeletedById" uuid,
        "RowVersion" bytea NOT NULL,
        CONSTRAINT "PK_SubscriptionPlanFeatures" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SubscriptionPlanFeatures_Features_FeatureId" FOREIGN KEY ("FeatureId") REFERENCES "Features" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_SubscriptionPlanFeatures_Features_FeatureId1" FOREIGN KEY ("FeatureId1") REFERENCES "Features" ("Id"),
        CONSTRAINT "FK_SubscriptionPlanFeatures_SubscriptionPlans_SubscriptionPlan~" FOREIGN KEY ("SubscriptionPlanId") REFERENCES "SubscriptionPlans" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "PasswordResetTokens" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Token" character varying(100) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UsedAt" timestamp with time zone,
        CONSTRAINT "PK_PasswordResetTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PasswordResetTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "TaskItems" (
        "Id" uuid NOT NULL,
        "ContactId" uuid NOT NULL,
        "InteractionId" uuid,
        "Title" character varying(200) NOT NULL,
        "Description" character varying(4000),
        "Status" character varying(32) NOT NULL DEFAULT 'pending',
        "Priority" character varying(32) NOT NULL DEFAULT 'normal',
        "AssignedToUserId" uuid,
        "DueDate" timestamp with time zone,
        "CompletedAt" timestamp with time zone,
        "RecurrenceRule" text,
        "ParentTaskId" uuid,
        "Source" text,
        "SourceReferenceId" text,
        "ConfidenceScore" double precision,
        "RequiresApproval" boolean NOT NULL,
        "ApprovalStatus" text,
        "Metadata" jsonb,
        "InteractionId1" uuid,
        "UserId" uuid,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedById" uuid,
        "UpdatedById" uuid,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "DeletedById" uuid,
        "RowVersion" bytea NOT NULL,
        CONSTRAINT "PK_TaskItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TaskItems_Contacts_ContactId" FOREIGN KEY ("ContactId") REFERENCES "Contacts" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_TaskItems_Interactions_InteractionId" FOREIGN KEY ("InteractionId") REFERENCES "Interactions" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_TaskItems_Interactions_InteractionId1" FOREIGN KEY ("InteractionId1") REFERENCES "Interactions" ("Id"),
        CONSTRAINT "FK_TaskItems_TaskItems_ParentTaskId" FOREIGN KEY ("ParentTaskId") REFERENCES "TaskItems" ("Id"),
        CONSTRAINT "FK_TaskItems_Users_AssignedToUserId" FOREIGN KEY ("AssignedToUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_TaskItems_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "UserPhoneNumbers" (
        "Id" uuid NOT NULL,
        "Number" character varying(20) NOT NULL,
        "Type" character varying(50),
        "UserId" uuid NOT NULL,
        "Label" text,
        "IsPrimary" boolean NOT NULL DEFAULT FALSE,
        "CreatedAt" timestamp with time zone NOT NULL,
        "VerifiedAt" timestamp with time zone,
        "IsVerified" boolean NOT NULL,
        CONSTRAINT "PK_UserPhoneNumbers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UserPhoneNumbers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "Subscriptions" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "StripeSubscriptionId" character varying(100),
        "PlanId" uuid NOT NULL,
        "StartDate" timestamp with time zone NOT NULL,
        "EndDate" timestamp with time zone,
        "Status" integer NOT NULL,
        "SeatsLimit" integer NOT NULL,
        "IsCallProcessingEnabled" boolean NOT NULL,
        "OrganizationSubscriptionId" uuid,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedById" uuid,
        "UpdatedById" uuid,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "DeletedById" uuid,
        "RowVersion" bytea NOT NULL,
        CONSTRAINT "PK_Subscriptions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Subscriptions_OrganizationSubscription_OrganizationSubscrip~" FOREIGN KEY ("OrganizationSubscriptionId") REFERENCES "OrganizationSubscription" ("Id"),
        CONSTRAINT "FK_Subscriptions_SubscriptionPlans_PlanId" FOREIGN KEY ("PlanId") REFERENCES "SubscriptionPlans" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Subscriptions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE TABLE "UserSubscriptionAssignments" (
        "UserId" uuid NOT NULL,
        "SubscriptionId" uuid NOT NULL,
        "OrganizationSubscriptionId" uuid NOT NULL,
        "AssignedAt" timestamp with time zone NOT NULL,
        "AssignedByUserId" uuid,
        "StartDate" timestamp with time zone,
        "EndDate" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        "DeactivatedAt" timestamp with time zone,
        "DeactivationReason" character varying(500),
        "Id" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CreatedById" uuid,
        "UpdatedById" uuid,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "DeletedById" uuid,
        "RowVersion" bytea NOT NULL,
        CONSTRAINT "PK_UserSubscriptionAssignments" PRIMARY KEY ("UserId", "SubscriptionId"),
        CONSTRAINT "FK_UserSubscriptionAssignments_OrganizationSubscription_Organi~" FOREIGN KEY ("OrganizationSubscriptionId") REFERENCES "OrganizationSubscription" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserSubscriptionAssignments_Subscriptions_SubscriptionId" FOREIGN KEY ("SubscriptionId") REFERENCES "Subscriptions" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UserSubscriptionAssignments_Users_AssignedByUserId" FOREIGN KEY ("AssignedByUserId") REFERENCES "Users" ("Id"),
        CONSTRAINT "FK_UserSubscriptionAssignments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_AccessAuditLogs_ContactId" ON "AccessAuditLogs" ("ContactId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_AccessAuditLogs_EntityType_EntityId" ON "AccessAuditLogs" ("EntityType", "EntityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_AccessAuditLogs_OrganizationId" ON "AccessAuditLogs" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_AccessAuditLogs_RequestingUserId" ON "AccessAuditLogs" ("RequestingUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_AccessAuditLogs_Timestamp" ON "AccessAuditLogs" ("Timestamp");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_AccessAuditLogs_UserId" ON "AccessAuditLogs" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_ActionItem_AssignedTo" ON "ActionItem" ("AssignedTo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_ActionItem_DueBy" ON "ActionItem" ("DueBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_ActionItem_InteractionId" ON "ActionItem" ("InteractionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_ActionItem_Priority" ON "ActionItem" ("Priority");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_ActionItem_Status" ON "ActionItem" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_AgentAssignment_AgentId" ON "AgentAssignment" ("AgentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_AgentAssignment_EmmaAnalysisId" ON "AgentAssignment" ("EmmaAnalysisId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Agents_AgentType" ON "Agents" ("AgentType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Agents_CreatedById" ON "Agents" ("CreatedById");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Agents_LastHeartbeat" ON "Agents" ("LastHeartbeat");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Agents_OrganizationId" ON "Agents" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Agents_Status" ON "Agents" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Agents_SubscriptionId" ON "Agents" ("SubscriptionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Attachment_InteractionId" ON "Attachment" ("InteractionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_ContactAssignments_AssignedAt" ON "ContactAssignments" ("AssignedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_ContactAssignments_AssignedByUserId" ON "ContactAssignments" ("AssignedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_ContactAssignments_ContactId" ON "ContactAssignments" ("ContactId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_ContactAssignments_InteractionId" ON "ContactAssignments" ("InteractionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_ContactAssignments_OrganizationId" ON "ContactAssignments" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_ContactAssignments_Priority" ON "ContactAssignments" ("Priority");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_ContactAssignments_ServiceContactId" ON "ContactAssignments" ("ServiceContactId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_ContactAssignments_Status" ON "ContactAssignments" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_ContactCollaborators_CollaboratorUserId" ON "ContactCollaborators" ("CollaboratorUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_ContactCollaborators_ContactId" ON "ContactCollaborators" ("ContactId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_ContactCollaborators_GrantedByUserId" ON "ContactCollaborators" ("GrantedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_ContactCollaborators_OrganizationId" ON "ContactCollaborators" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Contacts_Company" ON "Contacts" ("Company");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Contacts_LastContactedAt" ON "Contacts" ("LastContactedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Contacts_LastName_FirstName" ON "Contacts" ("LastName", "FirstName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Contacts_NextFollowUpAt" ON "Contacts" ("NextFollowUpAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Contacts_OrganizationId" ON "Contacts" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Contacts_OwnerId" ON "Contacts" ("OwnerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Contacts_RelationshipState" ON "Contacts" ("RelationshipState");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_ContactStateHistories_ChangedByUserId" ON "ContactStateHistories" ("ChangedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_ContactStateHistories_ContactId" ON "ContactStateHistories" ("ContactId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_ContactStateHistories_ToState" ON "ContactStateHistories" ("ToState");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_ContactStateHistories_TransitionDate" ON "ContactStateHistories" ("TransitionDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_ContactStates_AssignedUserId" ON "ContactStates" ("AssignedUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_ContactStates_ContactId" ON "ContactStates" ("ContactId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_ContactStates_ContactId_OrganizationId" ON "ContactStates" ("ContactId", "OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_ContactStates_OrganizationId" ON "ContactStates" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_ContactSummaries_ContactId_OrganizationId_SummaryType" ON "ContactSummaries" ("ContactId", "OrganizationId", "SummaryType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_DeviceTokens_DeviceId" ON "DeviceTokens" ("DeviceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_DeviceTokens_IsActive" ON "DeviceTokens" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_DeviceTokens_Platform" ON "DeviceTokens" ("Platform");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE UNIQUE INDEX "IX_DeviceTokens_Token" ON "DeviceTokens" ("Token");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_DeviceTokens_UserId" ON "DeviceTokens" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE UNIQUE INDEX "IX_EmailAddresses_Address" ON "EmailAddresses" ("Address");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_EmailAddresses_ContactId" ON "EmailAddresses" ("ContactId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_EmailAddresses_ContactId1" ON "EmailAddresses" ("ContactId1");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_EmailAddresses_UserId" ON "EmailAddresses" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_EmmaAnalyses_CreatedAt" ON "EmmaAnalyses" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_EmmaAnalyses_LeadStatus" ON "EmmaAnalyses" ("LeadStatus");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_EmmaAnalyses_MessageId" ON "EmmaAnalyses" ("MessageId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_EmmaTask_EmmaAnalysisId" ON "EmmaTask" ("EmmaAnalysisId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_InteractionEmbeddings_ContactId_OrganizationId_Timestamp" ON "InteractionEmbeddings" ("ContactId", "OrganizationId", "Timestamp");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE UNIQUE INDEX "IX_InteractionEmbeddings_InteractionId" ON "InteractionEmbeddings" ("InteractionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Interactions_AgentId" ON "Interactions" ("AgentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Interactions_AssignedToAgentId" ON "Interactions" ("AssignedToAgentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Interactions_AssignedToUserId" ON "Interactions" ("AssignedToUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Interactions_Channel" ON "Interactions" ("Channel");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Interactions_ContactId" ON "Interactions" ("ContactId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Interactions_CreatedAt" ON "Interactions" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Interactions_CreatedById" ON "Interactions" ("CreatedById");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Interactions_FollowUpBy" ON "Interactions" ("FollowUpBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Interactions_IsDeleted" ON "Interactions" ("IsDeleted");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Interactions_OrganizationId" ON "Interactions" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Interactions_OrganizationId1" ON "Interactions" ("OrganizationId1");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Interactions_ParentInteractionId" ON "Interactions" ("ParentInteractionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Interactions_Priority" ON "Interactions" ("Priority");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Interactions_Status" ON "Interactions" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Interactions_ThreadId" ON "Interactions" ("ThreadId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Interactions_Type" ON "Interactions" ("Type");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Interactions_UpdatedAt" ON "Interactions" ("UpdatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Messages_AgentId" ON "Messages" ("AgentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Messages_InteractionId" ON "Messages" ("InteractionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Messages_UserId" ON "Messages" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_OrganizationInvitations_AcceptedAt" ON "OrganizationInvitations" ("AcceptedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_OrganizationInvitations_Email" ON "OrganizationInvitations" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_OrganizationInvitations_ExpiresAt" ON "OrganizationInvitations" ("ExpiresAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_OrganizationInvitations_OrganizationId" ON "OrganizationInvitations" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_OrganizationInvitations_RevokedAt" ON "OrganizationInvitations" ("RevokedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE UNIQUE INDEX "IX_OrganizationInvitations_Token" ON "OrganizationInvitations" ("Token");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Organizations_Email" ON "Organizations" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Organizations_IsActive" ON "Organizations" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Organizations_Name" ON "Organizations" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Organizations_OwnerUserId" ON "Organizations" ("OwnerUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_OrganizationSubscription_OrganizationId" ON "OrganizationSubscription" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_OrganizationSubscription_SubscriptionPlanId" ON "OrganizationSubscription" ("SubscriptionPlanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Participant_InteractionId" ON "Participant" ("InteractionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE UNIQUE INDEX "IX_PasswordResetTokens_Token" ON "PasswordResetTokens" ("Token");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_PasswordResetTokens_UsedAt" ON "PasswordResetTokens" ("UsedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_PasswordResetTokens_UserId" ON "PasswordResetTokens" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_PhoneNumber_ContactId" ON "PhoneNumber" ("ContactId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_PhoneNumber_IsPrimary" ON "PhoneNumber" ("IsPrimary");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_PhoneNumber_Number" ON "PhoneNumber" ("Number");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_PhoneNumber_Type" ON "PhoneNumber" ("Type");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_RelatedEntity_InteractionId" ON "RelatedEntity" ("InteractionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_SubscriptionPlanFeatures_FeatureId" ON "SubscriptionPlanFeatures" ("FeatureId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_SubscriptionPlanFeatures_FeatureId1" ON "SubscriptionPlanFeatures" ("FeatureId1");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_SubscriptionPlanFeatures_SubscriptionPlanId" ON "SubscriptionPlanFeatures" ("SubscriptionPlanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_SubscriptionPlans_OrganizationId" ON "SubscriptionPlans" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Subscriptions_OrganizationSubscriptionId" ON "Subscriptions" ("OrganizationSubscriptionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Subscriptions_PlanId" ON "Subscriptions" ("PlanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Subscriptions_UserId" ON "Subscriptions" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_TaskItems_AssignedToUserId" ON "TaskItems" ("AssignedToUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_TaskItems_ContactId" ON "TaskItems" ("ContactId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_TaskItems_DueDate" ON "TaskItems" ("DueDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_TaskItems_InteractionId" ON "TaskItems" ("InteractionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_TaskItems_InteractionId1" ON "TaskItems" ("InteractionId1");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_TaskItems_ParentTaskId" ON "TaskItems" ("ParentTaskId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_TaskItems_Priority" ON "TaskItems" ("Priority");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_TaskItems_Status" ON "TaskItems" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_TaskItems_UserId" ON "TaskItems" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE UNIQUE INDEX "IX_Transcriptions_MessageId" ON "Transcriptions" ("MessageId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_UserPhoneNumbers_IsPrimary" ON "UserPhoneNumbers" ("IsPrimary");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_UserPhoneNumbers_UserId" ON "UserPhoneNumbers" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Users_IsActive" ON "Users" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_Users_OrganizationId" ON "Users" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_UserSubscriptionAssignments_AssignedByUserId" ON "UserSubscriptionAssignments" ("AssignedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_UserSubscriptionAssignments_OrganizationSubscriptionId" ON "UserSubscriptionAssignments" ("OrganizationSubscriptionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_UserSubscriptionAssignments_SubscriptionId" ON "UserSubscriptionAssignments" ("SubscriptionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    CREATE INDEX "IX_UserSubscriptionAssignments_UserId_IsActive" ON "UserSubscriptionAssignments" ("UserId", "IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "AccessAuditLogs" ADD CONSTRAINT "FK_AccessAuditLogs_Contacts_ContactId" FOREIGN KEY ("ContactId") REFERENCES "Contacts" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "AccessAuditLogs" ADD CONSTRAINT "FK_AccessAuditLogs_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "AccessAuditLogs" ADD CONSTRAINT "FK_AccessAuditLogs_Users_RequestingUserId" FOREIGN KEY ("RequestingUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "AccessAuditLogs" ADD CONSTRAINT "FK_AccessAuditLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "ActionItem" ADD CONSTRAINT "FK_ActionItem_Interactions_InteractionId" FOREIGN KEY ("InteractionId") REFERENCES "Interactions" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "AgentAssignment" ADD CONSTRAINT "FK_AgentAssignment_Agents_AgentId" FOREIGN KEY ("AgentId") REFERENCES "Agents" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "AgentAssignment" ADD CONSTRAINT "FK_AgentAssignment_EmmaAnalyses_EmmaAnalysisId" FOREIGN KEY ("EmmaAnalysisId") REFERENCES "EmmaAnalyses" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "Agents" ADD CONSTRAINT "FK_Agents_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "Agents" ADD CONSTRAINT "FK_Agents_Subscriptions_SubscriptionId" FOREIGN KEY ("SubscriptionId") REFERENCES "Subscriptions" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "Agents" ADD CONSTRAINT "FK_Agents_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "Attachment" ADD CONSTRAINT "FK_Attachment_Interactions_InteractionId" FOREIGN KEY ("InteractionId") REFERENCES "Interactions" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "CallMetadata" ADD CONSTRAINT "FK_CallMetadata_Messages_MessageId" FOREIGN KEY ("MessageId") REFERENCES "Messages" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "ContactAssignments" ADD CONSTRAINT "FK_ContactAssignments_Contacts_ContactId" FOREIGN KEY ("ContactId") REFERENCES "Contacts" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "ContactAssignments" ADD CONSTRAINT "FK_ContactAssignments_Contacts_ServiceContactId" FOREIGN KEY ("ServiceContactId") REFERENCES "Contacts" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "ContactAssignments" ADD CONSTRAINT "FK_ContactAssignments_Interactions_InteractionId" FOREIGN KEY ("InteractionId") REFERENCES "Interactions" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "ContactAssignments" ADD CONSTRAINT "FK_ContactAssignments_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "ContactAssignments" ADD CONSTRAINT "FK_ContactAssignments_Users_AssignedByUserId" FOREIGN KEY ("AssignedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "ContactCollaborators" ADD CONSTRAINT "FK_ContactCollaborators_Contacts_ContactId" FOREIGN KEY ("ContactId") REFERENCES "Contacts" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "ContactCollaborators" ADD CONSTRAINT "FK_ContactCollaborators_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "ContactCollaborators" ADD CONSTRAINT "FK_ContactCollaborators_Users_CollaboratorUserId" FOREIGN KEY ("CollaboratorUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "ContactCollaborators" ADD CONSTRAINT "FK_ContactCollaborators_Users_GrantedByUserId" FOREIGN KEY ("GrantedByUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "Contacts" ADD CONSTRAINT "FK_Contacts_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "Contacts" ADD CONSTRAINT "FK_Contacts_Users_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES "Users" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "ContactStateHistories" ADD CONSTRAINT "FK_ContactStateHistories_Users_ChangedByUserId" FOREIGN KEY ("ChangedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "ContactStates" ADD CONSTRAINT "FK_ContactStates_Users_AssignedUserId" FOREIGN KEY ("AssignedUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "DeviceTokens" ADD CONSTRAINT "FK_DeviceTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "EmailAddresses" ADD CONSTRAINT "FK_EmailAddresses_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "EmmaAnalyses" ADD CONSTRAINT "FK_EmmaAnalyses_Messages_MessageId" FOREIGN KEY ("MessageId") REFERENCES "Messages" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "InteractionEmbeddings" ADD CONSTRAINT "FK_InteractionEmbeddings_Interactions_InteractionId" FOREIGN KEY ("InteractionId") REFERENCES "Interactions" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "Interactions" ADD CONSTRAINT "FK_Interactions_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "Interactions" ADD CONSTRAINT "FK_Interactions_Organizations_OrganizationId1" FOREIGN KEY ("OrganizationId1") REFERENCES "Organizations" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "Interactions" ADD CONSTRAINT "FK_Interactions_Users_AssignedToUserId" FOREIGN KEY ("AssignedToUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "Interactions" ADD CONSTRAINT "FK_Interactions_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "Messages" ADD CONSTRAINT "FK_Messages_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "OrganizationInvitations" ADD CONSTRAINT "FK_OrganizationInvitations_Organizations_OrganizationId" FOREIGN KEY ("OrganizationId") REFERENCES "Organizations" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    ALTER TABLE "Organizations" ADD CONSTRAINT "FK_Organizations_Users_OwnerUserId" FOREIGN KEY ("OwnerUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250812161632_AddOrganizationInvitations') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250812161632_AddOrganizationInvitations', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250813233428_AddOrganizationPlanId') THEN
    ALTER TABLE "Organizations" ADD "PlanId" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250813233428_AddOrganizationPlanId') THEN
    ALTER TABLE "Users"
                      ADD COLUMN IF NOT EXISTS "VerifiedAt" timestamptz NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250813233428_AddOrganizationPlanId') THEN
    CREATE INDEX IF NOT EXISTS "IX_Organizations_PlanId"
                      ON "Organizations" ("PlanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250813233428_AddOrganizationPlanId') THEN
    UPDATE "Organizations"
                        SET "PlanId" = CASE "PlanType"
                            WHEN 0 THEN 'Free'
                            WHEN 1 THEN 'Basic'
                            WHEN 2 THEN 'Pro'
                            WHEN 3 THEN 'Enterprise'
                            ELSE "PlanId"
                        END
                      WHERE "PlanId" IS NULL
                        AND "PlanType" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250813233428_AddOrganizationPlanId') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250813233428_AddOrganizationPlanId', '8.0.8');
    END IF;
END $EF$;
COMMIT;

